trainingInput:
  hyperparameters:
    goal: MINIMIZE
    maxTrials: 10
    maxParallelTrials: 5
    hyperparameterMetricTag: val_loss
    enableTrialEarlyStopping: TRUE
    params:
      - parameterName: learning_rate
        type: DOUBLE
        minValue: 0.0001
        maxValue: 0.01
        scaleType: UNIT_LOG_SCALE
      - parameterName: batch_size
        type: DISCRETE
        discreteValues: [16, 32, 64, 128]
      - parameterName: epochs
        type: INTEGER
        minValue: 5
        maxValue: 20
        scaleType: UNIT_LINEAR_SCALE
